# Generated by Django 3.2.7 on 2021-10-04 20:37

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paintingcategory',
            options={'ordering': ['name'], 'verbose_name': 'Painting Category', 'verbose_name_plural': 'Painting Categories'},
        ),
        migrations.RemoveField(
            model_name='paintingdetailpage',
            name='technical_details',
        ),
        migrations.AddField(
            model_name='paintingdetailpage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='catalog.PaintingCategory'),
        ),
        migrations.AddField(
            model_name='paintingdetailpage',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paintingdetailpage',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paintingdetailpage',
            name='width',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paintingcategory',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name'),
        ),
        migrations.AlterField(
            model_name='paintingpagetag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='catalog.paintingdetailpage'),
        ),
        migrations.DeleteModel(
            name='PaintingPagePaintingCategory',
        ),
    ]
