# Generated by Django 3.2.8 on 2021-10-31 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20211028_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paintingdetailpage',
            name='initial_inventory',
        ),
        migrations.AddField(
            model_name='paintingdetailpage',
            name='dbreference',
            field=models.CharField(blank=True, default='a', help_text='Entry from initial Excel Inventory by JMC, for internal needs only', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paintingdetailpage',
            name='remark',
            field=models.CharField(blank=True, default='a', help_text='Entry from initial Excel Inventory by JMC, for internal needs only', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='paintingdetailpage',
            name='signature',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
